### PR TITLE
Update zzuf maps

### PR DESCRIPTION
**Pull request by zzufx**
Updates Deadwood and Armature. I don't think these maps ever get played on this server, but I just didn't like seeing such old versions.

### CODE REVIEW

**Comment by TheRealPear** [comment]
Thanks for opening a pull request. Unfortunately, Warzone is still using PGM 0.15. Since Deadwood is using sound actions, I don't know if the map would load properly, otherwise you may have to comment it out just in case.

**Comment by zzufx** [comment]
Ah, I thought it'd have been updated by now - if you want to you can edit those out and make it follow Warzone's versioning (so it'd be 1.0.5), otherwise feel free to close this.

**Comment by TheRealPear** [comment]
Thanks for your patience. After 5 months, Warzone has finally updated its version of PGM. Would you be willing to update this pull request to include newer versions of the maps here?

**Comment by zzufx** [comment]
Sure thing - Deadwood now uses an include file tho, so not sure how that's set up here

**Comment by TheRealPear** [comment]
> Deadwood now uses an include file tho, so not sure how that's set up here
This is still undecided for now. We have a [repo](https://github.com/Warzone/Includes) for it like what was planned in OCC, but I am still thinking about using PublicMaps for it instead.

**Pull request merged**
