### PR TITLE
Desolate Gully: Add multiple items to item-remove

### PR DESCRIPTION
**Pull request by Wesdial**
This PR will prevent several items not to be dropped 
- Stone Sword
- Stone Pickaxe
- Stone Axe
- Bow
Hopefully I did it correctly, lol

### CODE REVIEW

**Comment by master00ofdsiware** [comment]
These items area already on toolrepair. They should be in one section or the other, not both.

**Comment by Wesdial** [comment]
Hmm, didn't know, but the issue still stands, these items still drop on death and its extremely obnoxious everytime I kill someone, my inventory gets filled with these items.

**Comment by master00ofdsiware** [comment]
They drop on death but they don't go into your inventory when picked up. They instead "repair" your versions of those tools.

It makes no difference here because the tools are already unbreakable.

**Comment by Wesdial** [comment]
Well, that's weird, becuase last time I played on this map the items dropped on death and they were picked up and my inventory got filled with a bunch of bows, axes, pickaxes and swords, so I don't really know. I might test it on my local server to see. and might even record a clip while i'm at it to show you.

**Comment by Wesdial** [comment]
> They do actually fill up the inventory, just tested. The problem here is that the items under tool repair should be in-between <tool></tool> tags, not <item>. That's why they're not fusing with existing tools in your inventory

Should be fixed now, hopefully.

**Pull request merged**
