### PR TITLE
Add "The Asylum" and "Euphoria Town"

### PR DESCRIPTION
**Pull request by Wesdial**

### CODE REVIEW

**Comment by BTKingly** [comment]
Before I merge this, I just want to point out a few things that I noticed, either bugs or that I'm not sure are intentional.
On The Asylum as beasts, you can;
- double jump over the bars blocking the staircase. While there is a ladder to go upstairs for hunters, it's not super clear. Not sure if beasts are supposed to be able to jump this
- double jump out of the map

**Comment by BTKingly** [comment]
I can also double jump out of Euphoria Town

**Comment by Wesdial** [comment]
> * double jump over the bars blocking the staircase. While there is a ladder to go upstairs for hunters, it's not super clear. Not sure if beasts are supposed to be able to jump this

Yes, this is intended.

> * double jump out for the map in "The Asylum" and "Euphoria Town"

Should be fixed now.

**Comment by master00ofdsiware** [comment]
`<?xml version="1.0.2"?>` ??
Also, please fix the indentation

**Comment by Wesdial** [comment]
That should be it hopefully.

**Pull request merged**
