### PR TITLE
[WIP - BedWars] Add "Bodiam Castle"

### PR DESCRIPTION
**Pull request by TheRealPear**
### Map Name
Bodiam Castle (formerly `BedWarsTest`)

### Gamemode(s)
DTM + Blitz 

### Description & Team Sizes
A combination of DTM and Blitz with custom Bed Wars features. This map supports four teams of four (4v4v4v4), totaling 16 players with a minimum of two players per team.

### Screenshots
[Click here to view Imgur album](https://imgur.com/a/pmuJeu2)

### XML
The XML can be found on [GitHub Gist](https://gist.github.com/TheRealPear/8df8c99c869d6f77d1269f517f54b5f7) or [here](https://github.com/TheRealPear/PublicMaps/blob/bedwarstest/DTM/Standard/Bodiam%20Castle/map.xml).

### Map Download
The map files can be found [here](https://github.com/TheRealPear/PublicMaps/tree/bedwarstest/DTM/Standard/Bodiam%20Castle).

---

### Map Checklist
- [X] Contains a `map.xml` file with valid syntax and formatting.
- [X] The `map.xml` uses proto `1.4.0` or above (older or legacy maps are exempt, so long as the XML works).
- [X] The `map.xml` explicitly [sets the gamemode](https://pgm.dev/docs/modules/general/main#map-gamemode) (for stat-tracking).
- [X] The `map.xml` has correctly credited the map authors and contributors.
- [X] Contains `map.png` file (`290x246`).
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [x] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license.

### To-do list
- [X] Teams creation
- [X] Spawns defined
- [X] Default kit creation
- [x] Monuments
- [x] Blitz module and sudden death filter
- [x] Spawn protections
- [x] Generators
- [X] Villager NPCs for item upgrades (will be done manually, like [Antiquis](https://github.com/Warzone/PublicMaps/tree/main/DTM/Standard/Antiquis))
~~- [ ] Armor upgrade (only leggings and boot) for individual players~~
- [x] Block place/destroy filter (need to stop people from editing non-user placed blocks)
- [x] ItemRemove, ItemKeep, ItemRepair, and ArmorKeep
- [X] Build height
- [X] Respawn module configured
- [X] Hunger depletion disabled
- [x] Disable crafting
- [x] Team chest filters (allow enemies to open an eliminated team's chest)
---

### Known Issues
* Blitz info appears above monument status in scoreboard
* Delay timers from spawners may mess up occasionally
* ~~Every monuments appear to be owned by all teams in the scoreboard (see https://github.com/PGMDev/PGM/issues/967)~~ Special thanks to Pablo for fixing it
* Diamond (generators and as a currency) are useless for now since no team upgrades
* ~~Enderchests are present in the map, but are currently disabled until it is fixed with PGM~~
* Glass blocks, while immune to TNT explosions, won't protect the inside if built as a dome.

### CODE REVIEW

**Comment by master00ofdsiware** [comment]
I know this is a draft PR, but please eventually give the map a real name.

**Comment by TheRealPear** [comment]
This was discussed in the mapmaking channel, but I will be posting a summary of it on here:
* Scoreboards will probably never show up properly because all 4 teams have the same block as their monument, unlike other maps with colored wools or similar variants. This is a big issue on clients below 1.18 due to character limits.
* This is the second(?) map with a four-person DTM and it's pretty buggy in general and not even officially supported. I don't think it's really worth trying to make a Bed Wars game work with PGM, so I'll probably change it to regular DTW, but with having to collect your own supplies and more emphasis on defending the wool.

**Comment by TheRealPear** [comment]
Map has been given a new name. I've been working on a [spreadsheet that contains all the items that will be given to players in exchange for iron/gold/emeralds via villager trading](https://docs.google.com/spreadsheets/d/1ClfUREzMwWjDAX4o7ghGxhu48VqFdmq-sz2d9fLPsIU/edit?usp=sharing).

**Comment by TheRealPear** [comment]
The map is close to being complete and almost playable for most parts. Just need to figure out how to handle sudden deaths (maybe with world border showing up and shrinking instead of ender dragon?) and team resource upgrades with diamonds.

**Comment by TheRealPear** [comment]
Everything has been tested and confirmed working so far. I'd like to remind people that this is not a 1:1 recreation of Hypixel's Bed Wars, so some items are missing because of PGM limitations or gameplay issue/complexity.

List of missing features:
* Throwable fireballs -> PGM limitation that should be fixed soon
* Team-wide kits upgrade (including resource upgrades with diamond) -> PGM limitation that should be introduced in an update soon
* Removing wooden sword once user has upgraded to a better sword -> PGM limitation
* Enderchests -> PGM limitation as the content will save across matches
* Tower defense builder - gameplay complexity & PGM limitation

Most of these will be added in a future update. I'd like to thank everyone in Warzone and OCC involved in the creation of this map for the help and support you've shown.

**Pull request merged**
