### PR TITLE
Update "BalloonsDTM" to proto 1.4.0

### PR DESCRIPTION
**Pull request by Wesdial**

### CODE REVIEW

**Comment by CrazyisCreeps** [comment]
What happened to the spawn protection regions?

Also can you please capitalize the message on line 85 for the not-map build region.

Just to check, was the map tested to ensure it works?

**Comment by Wesdial** [comment]
Sorry, It was late at night and I was rushing it. but it should be fixed now.

-  What happened to the spawn protection regions?

> Added a spawn protection region.





- Also can you please capitalize the message on line 85 for the not-map build region.

> Fixed. and fixed some indentation as well

- Just to check, was the map tested to ensure it works?

> Yes, I always test the maps before submiting or updating them, and yesterday, it seemed to work just fine, I might've missed the spawn protection thing.

**Comment by BTKingly** [comment]
For the objective message, could you  un-pluralise monuments? Since there's only one per side, it should be singular.

**Comment by Wesdial** [comment]
yep, done.

**Comment by CrazyisCreeps** [comment]
Okay this looks awesome! One last quick question, why did you bump the team sizes from 12 to 15?

**Comment by Wesdial** [comment]
I'm so sorry, I keep making dumb mistakes, my bad. Fixed.

**Pull request merged**
