### PR TITLE
Add "Target" by n6cr

### PR DESCRIPTION
**Pull request by TheRealPear**
### Map Name
Target

### Gamemode(s)
KoTH

### Description & Team Sizes
This is a 3v3 small-sized KoTH map with three hills. The smaller side hills are worth one point and takes 3 seconds to capture while the larger central hill is worth 3 points and takes 5 seconds to capture.

### Screenshots
https://imgur.com/a/cBtd6b2

### XML
https://gist.github.com/TheRealPear/afc6568752b700d1faf12f192cdf9298 
(a copy of the xml is also available in the mega.nz link below)

### Map Download
https://mega.nz/folder/gfREiJjZ#Lkwec2SngOakfpXRcExBOQ

---

- [x] Contains a `map.xml` file with valid syntax and formatting.
- [x] The `map.xml` uses proto `1.4.0` or above (older or legacy maps are exempt, so long as the XML works).
- [x] The `map.xml` explicitly [sets the gamemode](https://pgm.dev/docs/modules/general/main#map-gamemode) (for stat-tracking).
- [x] The `map.xml` has correctly credited the map authors and contributors.
- [x] Contains `map.png` file (`290x246`).
- [x] The map was built for (or has been converted to) Minecraft 1.8.
- [x] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [x] I agree to submit this map under a commercial, [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license.

---

### Known Issues
n/a

### CODE REVIEW

**Comment by TBG1000** [comment]
Looks clean. Reminds me of some other map I can't quite put my finger on, but maybe that's just me. Was this inspired by some other map?

Also, I'm aware this is a draft PR but let this comment be a precedent for any future submissions: use [GitHub Gist](https://gist.github.com/) for XMLs and do upload the map files to a file sharing service. Such requirements weren't actually enforced in the early stages of the switch to PGM out of simplicity, but I believe the repo has matured enough to start following them.

I know it may be a hassle for the map author(s) or people creating PRs on this repo, but the purpose of independently uploading XMLs or map files elsewhere is for a) ease of access and b) safekeeping. If repo branches are deleted, folders are renamed, or files are moved somewhere else, it may be a burden to look for them again. Look at #18 if you'd like an example of this, the links for the XML and map download take you to the 404 GitHub page (because the map was renamed, etc).

Additionally, it is much simpler for a map developer, staff member or even community users to have a direct download of a map instead of downloading a repo, cloning a fork or manually downloading each individual file off of GitHub.

The PR template will be edited to emphasize these changes.

**Comment by BTKingly** [comment]
Can the spectator spawn be raised? Chests can be accessed from the map below. (or place a block below them to prevent?)

**Comment by TheRealPear** [comment]
> Can the spectator spawn be raised?

Fixed in 09052254886ed77bd9ba997275ba9acf44fe63d4 by moving it so it does not cover the top part of the map.

I have edited the original post to include an Imgur album, a GitHub Gist copy of the map.xml and a mega.nz link to download the map.

**Comment by master00ofdsiware** [comment]
Nice and clean map, good work. Thanks for the submission! This needs some gameplay testing on Warzone and then we can add it to a rotation.

**Pull request merged**
