### PR TITLE
Update "Hyral Skylands" to proto 1.4.0

### PR DESCRIPTION
**Pull request by Wesdial**
Note: Unlike the first PR, this one should have no errors or mistakes at all, I double and triple checked and tested the map before making a Pull Request. If there happens to be a mistake, then, oh well.

### CODE REVIEW

**Comment by CrazyisCreeps** [comment]
This is awesome! You'll see a few things I pointed out, but otherwise it looks good.

There is one thing though. When proto 1.3.0 was first introduced, there was an issue with regions being off by a block, which was later fixed in proto 1.3.1. When a map is updated out of proto 1.3.0, the regions end up off by a block, as the way regions were done was somehow different. It's an only that only persists with this exact proto.

So if you could do be a hot favour and just ensure that the regions seem to be where they should be, and make any changes to the regions as you see fit, that would be incredible. Otherwise, the regions will be off by a block.

**Comment by Wesdial** [comment]
Yeah, should be good to go now. just tested.

**Comment by CrazyisCreeps** [comment]
Cool, so yea just see the reviews and then it's good to merge!

**Comment by Wesdial** [comment]
uh, hey, I might be missing something, but there are no reviews?

**Comment by TBG1000** [comment]
@CrazyisCreeps help this man

**Comment by CrazyisCreeps** [comment]
Screenshot_20220401-170611

**Comment by Wesdial** [comment]
Done

**Pull request merged**
